[Data]
graph_signal_matrix_filename = data/METR-LA/samples_24_24_5.npz
distance_csv_path = data/METR-LA/METR-LA.csv
dataset_name = METRLA_1dim
num_of_vertices = 207
time_slice_size = 5
train_ratio = 0.7
val_ratio = 0.1
test_ratio = 0.2
data_file = data/METR-LA/METR-LA.npz
output_dir = data/METR-LA

[Training]
use_nni = 0
gpu = 1
ctx = 0
L = 2
K = 16
d = 8
mode = train
batch_size = 64
epochs = 200
learning_rate = 0.001
patience = 10
decay_epoch = 10
num_his = 24
num_pred = 24
in_channels = 1
out_channels = 1
T_miss_len = 24
node_miss_rate = 0.1
self_weight_dis = 0.05
reference = 3
order = 3
